[project]
name = "dashboard-gen"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pydantic>=2.11.5",
    "requests>=2.31.0",
    "python-dotenv>=1.0.0",
    "pytest>=8.4.0",
]

[tool.ruff]
line-length = 119
